//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __HRTImagingToolResource_h__
#define __HRTImagingToolResource_h__
class wxHITDialog_Base : public wxDialog {
protected:
 wxListBox* m_listBoxFiles;
 wxTextCtrl* m_textCtrlLog;
 wxButton* m_buttonAddFiles;
 wxButton* m_buttonRemoveFiles;
 wxStaticText* m_staticTextState;
 wxButton* m_buttonStartStop;
 wxButton* m_buttonClose;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("wxHITDialog_Base"), wxT("wxDialog"));
  m_listBoxFiles = XRCCTRL(*this,"m_listBoxFiles",wxListBox);
  m_textCtrlLog = XRCCTRL(*this,"m_textCtrlLog",wxTextCtrl);
  m_buttonAddFiles = XRCCTRL(*this,"m_buttonAddFiles",wxButton);
  m_buttonRemoveFiles = XRCCTRL(*this,"m_buttonRemoveFiles",wxButton);
  m_staticTextState = XRCCTRL(*this,"m_staticTextState",wxStaticText);
  m_buttonStartStop = XRCCTRL(*this,"m_buttonStartStop",wxButton);
  m_buttonClose = XRCCTRL(*this,"m_buttonClose",wxButton);
 }
public:
wxHITDialog_Base(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class wxHITLive_Base : public wxDialog {
protected:
 wxPanel* m_LiveImageWindow;
 wxPanel* m_LivePreview;
 wxStaticText* m_lblStateBig;
 wxStaticText* m_lblState;
 wxListBox* m_listFilenames;
 wxCheckBox* m_ctrlCalibPattern;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("wxHITLive_Base"), wxT("wxDialog"));
  m_LiveImageWindow = XRCCTRL(*this,"m_LiveImageWindow",wxPanel);
  m_LivePreview = XRCCTRL(*this,"m_LivePreview",wxPanel);
  m_lblStateBig = XRCCTRL(*this,"m_lblStateBig",wxStaticText);
  m_lblState = XRCCTRL(*this,"m_lblState",wxStaticText);
  m_listFilenames = XRCCTRL(*this,"m_listFilenames",wxListBox);
  m_ctrlCalibPattern = XRCCTRL(*this,"m_ctrlCalibPattern",wxCheckBox);
 }
public:
wxHITLive_Base(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class wxHITParameterDialog_Base : public wxDialog {
protected:
 wxButton* m_buttonPreset2D;
 wxButton* m_buttonPresetSNP;
 wxButton* m_buttonPreset3DVoxel;
 wxScrolledWindow* m_scrolledWindowParameters;
 wxStaticText* m_staticTextPar01;
 wxSpinCtrl* m_spinCtrlPar01;
 wxStaticText* m_staticTextPar02;
 wxSpinCtrl* m_spinCtrlPar02;
 wxStaticText* m_staticTextPar03;
 wxCheckBox* m_checkBoxPar03;
 wxStaticText* m_staticTextPar04;
 wxCheckBox* m_checkBoxPar04;
 wxStaticText* m_staticTextPar05;
 wxCheckBox* m_checkBoxPar05;
 wxStaticText* m_staticTextPar06;
 wxFilePickerCtrl* m_filePickerPar06;
 wxStaticText* m_staticTextPar07;
 wxSpinCtrl* m_spinCtrlPar07;
 wxStaticText* m_staticTextPar08;
 wxChoice* m_choicePar08;
 wxStaticText* m_staticTextPar09;
 wxSpinCtrlDouble* m_spinCtrlDoublePar09;
 wxStaticText* m_staticTextPar10;
 wxSpinCtrl* m_spinCtrlPar10;
 wxStaticText* m_staticTextPar11;
 wxSpinCtrl* m_spinCtrlPar11;
 wxStaticText* m_staticTextPar12;
 wxSpinCtrl* m_spinCtrlPar12;
 wxStaticText* m_staticTextPar13;
 wxSpinCtrl* m_spinCtrlPar13;
 wxStaticText* m_staticTextPar14;
 wxSpinCtrl* m_spinCtrlPar14;
 wxStaticText* m_staticTextPar15;
 wxChoice* m_choicePar15;
 wxStaticText* m_staticTextPar16;
 wxChoice* m_choicePar16;
 wxStaticText* m_staticTextPar17;
 wxSpinCtrlDouble* m_spinCtrlDoublePar17;
 wxStaticText* m_staticTextPar18;
 wxSpinCtrlDouble* m_spinCtrlDoublePar18;
 wxStaticText* m_staticTextPar19;
 wxSpinCtrlDouble* m_spinCtrlDoublePar19;
 wxStaticText* m_staticTextPar20;
 wxSpinCtrlDouble* m_spinCtrlDoublePar20;
 wxStaticText* m_staticTextPar21;
 wxSpinCtrlDouble* m_spinCtrlDoublePar21;
 wxStaticText* m_staticTextPar22;
 wxSpinCtrl* m_spinCtrlPar22;
 wxStaticText* m_staticTextPar23;
 wxCheckBox* m_checkBoxPar23;
 wxStaticText* m_staticTextPar24;
 wxCheckBox* m_checkBoxPar24;
 wxStaticText* m_staticTextPar25;
 wxChoice* m_choicePar25;
 wxStaticText* m_staticTextPar26;
 wxCheckBox* m_checkBoxPar26;
 wxStaticText* m_staticTextPar27;
 wxCheckBox* m_checkBoxPar27;
 wxStaticText* m_staticTextPar28;
 wxFilePickerCtrl* m_filePickerPar28;
 wxStaticText* m_staticTextPar29;
 wxSpinCtrl* m_spinCtrlPar29;
 wxStaticText* m_staticTextPar30;
 wxChoice* m_choicePar30;
 wxStaticText* m_staticTextPar31;
 wxChoice* m_choicePar31;
 wxStaticText* m_staticTextPar32;
 wxSpinCtrl* m_spinCtrlPar32;
 wxStaticText* m_staticTextPar33;
 wxSpinCtrl* m_spinCtrlPar33;
 wxStaticText* m_staticTextPar34;
 wxSpinCtrlDouble* m_spinCtrlDoublePar34;
 wxStaticText* m_staticTextPar35;
 wxSpinCtrlDouble* m_spinCtrlDoublePar35;
 wxStaticText* m_staticTextPar36;
 wxCheckBox* m_checkBoxPar36;
 wxStaticText* m_staticTextPar37;
 wxCheckBox* m_checkBoxPar37;
 wxStaticText* m_staticTextPar38;
 wxCheckBox* m_checkBoxPar38;
 wxPanel* m_panelHelp;
 wxStaticText* m_staticTextParameterName;
 wxTextCtrl* m_textCtrlParameterHelp;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("wxHITParameterDialog_Base"), wxT("wxDialog"));
  m_buttonPreset2D = XRCCTRL(*this,"m_buttonPreset2D",wxButton);
  m_buttonPresetSNP = XRCCTRL(*this,"m_buttonPresetSNP",wxButton);
  m_buttonPreset3DVoxel = XRCCTRL(*this,"m_buttonPreset3DVoxel",wxButton);
  m_scrolledWindowParameters = XRCCTRL(*this,"m_scrolledWindowParameters",wxScrolledWindow);
  m_staticTextPar01 = XRCCTRL(*this,"m_staticTextPar01",wxStaticText);
  m_spinCtrlPar01 = XRCCTRL(*this,"m_spinCtrlPar01",wxSpinCtrl);
  m_staticTextPar02 = XRCCTRL(*this,"m_staticTextPar02",wxStaticText);
  m_spinCtrlPar02 = XRCCTRL(*this,"m_spinCtrlPar02",wxSpinCtrl);
  m_staticTextPar03 = XRCCTRL(*this,"m_staticTextPar03",wxStaticText);
  m_checkBoxPar03 = XRCCTRL(*this,"m_checkBoxPar03",wxCheckBox);
  m_staticTextPar04 = XRCCTRL(*this,"m_staticTextPar04",wxStaticText);
  m_checkBoxPar04 = XRCCTRL(*this,"m_checkBoxPar04",wxCheckBox);
  m_staticTextPar05 = XRCCTRL(*this,"m_staticTextPar05",wxStaticText);
  m_checkBoxPar05 = XRCCTRL(*this,"m_checkBoxPar05",wxCheckBox);
  m_staticTextPar06 = XRCCTRL(*this,"m_staticTextPar06",wxStaticText);
  m_filePickerPar06 = XRCCTRL(*this,"m_filePickerPar06",wxFilePickerCtrl);
  m_staticTextPar07 = XRCCTRL(*this,"m_staticTextPar07",wxStaticText);
  m_spinCtrlPar07 = XRCCTRL(*this,"m_spinCtrlPar07",wxSpinCtrl);
  m_staticTextPar08 = XRCCTRL(*this,"m_staticTextPar08",wxStaticText);
  m_choicePar08 = XRCCTRL(*this,"m_choicePar08",wxChoice);
  m_staticTextPar09 = XRCCTRL(*this,"m_staticTextPar09",wxStaticText);
  m_spinCtrlDoublePar09 = XRCCTRL(*this,"m_spinCtrlDoublePar09",wxSpinCtrlDouble);
  m_staticTextPar10 = XRCCTRL(*this,"m_staticTextPar10",wxStaticText);
  m_spinCtrlPar10 = XRCCTRL(*this,"m_spinCtrlPar10",wxSpinCtrl);
  m_staticTextPar11 = XRCCTRL(*this,"m_staticTextPar11",wxStaticText);
  m_spinCtrlPar11 = XRCCTRL(*this,"m_spinCtrlPar11",wxSpinCtrl);
  m_staticTextPar12 = XRCCTRL(*this,"m_staticTextPar12",wxStaticText);
  m_spinCtrlPar12 = XRCCTRL(*this,"m_spinCtrlPar12",wxSpinCtrl);
  m_staticTextPar13 = XRCCTRL(*this,"m_staticTextPar13",wxStaticText);
  m_spinCtrlPar13 = XRCCTRL(*this,"m_spinCtrlPar13",wxSpinCtrl);
  m_staticTextPar14 = XRCCTRL(*this,"m_staticTextPar14",wxStaticText);
  m_spinCtrlPar14 = XRCCTRL(*this,"m_spinCtrlPar14",wxSpinCtrl);
  m_staticTextPar15 = XRCCTRL(*this,"m_staticTextPar15",wxStaticText);
  m_choicePar15 = XRCCTRL(*this,"m_choicePar15",wxChoice);
  m_staticTextPar16 = XRCCTRL(*this,"m_staticTextPar16",wxStaticText);
  m_choicePar16 = XRCCTRL(*this,"m_choicePar16",wxChoice);
  m_staticTextPar17 = XRCCTRL(*this,"m_staticTextPar17",wxStaticText);
  m_spinCtrlDoublePar17 = XRCCTRL(*this,"m_spinCtrlDoublePar17",wxSpinCtrlDouble);
  m_staticTextPar18 = XRCCTRL(*this,"m_staticTextPar18",wxStaticText);
  m_spinCtrlDoublePar18 = XRCCTRL(*this,"m_spinCtrlDoublePar18",wxSpinCtrlDouble);
  m_staticTextPar19 = XRCCTRL(*this,"m_staticTextPar19",wxStaticText);
  m_spinCtrlDoublePar19 = XRCCTRL(*this,"m_spinCtrlDoublePar19",wxSpinCtrlDouble);
  m_staticTextPar20 = XRCCTRL(*this,"m_staticTextPar20",wxStaticText);
  m_spinCtrlDoublePar20 = XRCCTRL(*this,"m_spinCtrlDoublePar20",wxSpinCtrlDouble);
  m_staticTextPar21 = XRCCTRL(*this,"m_staticTextPar21",wxStaticText);
  m_spinCtrlDoublePar21 = XRCCTRL(*this,"m_spinCtrlDoublePar21",wxSpinCtrlDouble);
  m_staticTextPar22 = XRCCTRL(*this,"m_staticTextPar22",wxStaticText);
  m_spinCtrlPar22 = XRCCTRL(*this,"m_spinCtrlPar22",wxSpinCtrl);
  m_staticTextPar23 = XRCCTRL(*this,"m_staticTextPar23",wxStaticText);
  m_checkBoxPar23 = XRCCTRL(*this,"m_checkBoxPar23",wxCheckBox);
  m_staticTextPar24 = XRCCTRL(*this,"m_staticTextPar24",wxStaticText);
  m_checkBoxPar24 = XRCCTRL(*this,"m_checkBoxPar24",wxCheckBox);
  m_staticTextPar25 = XRCCTRL(*this,"m_staticTextPar25",wxStaticText);
  m_choicePar25 = XRCCTRL(*this,"m_choicePar25",wxChoice);
  m_staticTextPar26 = XRCCTRL(*this,"m_staticTextPar26",wxStaticText);
  m_checkBoxPar26 = XRCCTRL(*this,"m_checkBoxPar26",wxCheckBox);
  m_staticTextPar27 = XRCCTRL(*this,"m_staticTextPar27",wxStaticText);
  m_checkBoxPar27 = XRCCTRL(*this,"m_checkBoxPar27",wxCheckBox);
  m_staticTextPar28 = XRCCTRL(*this,"m_staticTextPar28",wxStaticText);
  m_filePickerPar28 = XRCCTRL(*this,"m_filePickerPar28",wxFilePickerCtrl);
  m_staticTextPar29 = XRCCTRL(*this,"m_staticTextPar29",wxStaticText);
  m_spinCtrlPar29 = XRCCTRL(*this,"m_spinCtrlPar29",wxSpinCtrl);
  m_staticTextPar30 = XRCCTRL(*this,"m_staticTextPar30",wxStaticText);
  m_choicePar30 = XRCCTRL(*this,"m_choicePar30",wxChoice);
  m_staticTextPar31 = XRCCTRL(*this,"m_staticTextPar31",wxStaticText);
  m_choicePar31 = XRCCTRL(*this,"m_choicePar31",wxChoice);
  m_staticTextPar32 = XRCCTRL(*this,"m_staticTextPar32",wxStaticText);
  m_spinCtrlPar32 = XRCCTRL(*this,"m_spinCtrlPar32",wxSpinCtrl);
  m_staticTextPar33 = XRCCTRL(*this,"m_staticTextPar33",wxStaticText);
  m_spinCtrlPar33 = XRCCTRL(*this,"m_spinCtrlPar33",wxSpinCtrl);
  m_staticTextPar34 = XRCCTRL(*this,"m_staticTextPar34",wxStaticText);
  m_spinCtrlDoublePar34 = XRCCTRL(*this,"m_spinCtrlDoublePar34",wxSpinCtrlDouble);
  m_staticTextPar35 = XRCCTRL(*this,"m_staticTextPar35",wxStaticText);
  m_spinCtrlDoublePar35 = XRCCTRL(*this,"m_spinCtrlDoublePar35",wxSpinCtrlDouble);
  m_staticTextPar36 = XRCCTRL(*this,"m_staticTextPar36",wxStaticText);
  m_checkBoxPar36 = XRCCTRL(*this,"m_checkBoxPar36",wxCheckBox);
  m_staticTextPar37 = XRCCTRL(*this,"m_staticTextPar37",wxStaticText);
  m_checkBoxPar37 = XRCCTRL(*this,"m_checkBoxPar37",wxCheckBox);
  m_staticTextPar38 = XRCCTRL(*this,"m_staticTextPar38",wxStaticText);
  m_checkBoxPar38 = XRCCTRL(*this,"m_checkBoxPar38",wxCheckBox);
  m_panelHelp = XRCCTRL(*this,"m_panelHelp",wxPanel);
  m_staticTextParameterName = XRCCTRL(*this,"m_staticTextParameterName",wxStaticText);
  m_textCtrlParameterHelp = XRCCTRL(*this,"m_textCtrlParameterHelp",wxTextCtrl);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
 }
public:
wxHITParameterDialog_Base(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlResource();
#endif
